import numpy as np
ele=list(map(int,input("Enter the elements of the array separated by space: ").split()))
arr=np.array(ele)
print(arr)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.percentile(arr,25))
print(np.percentile(arr,50))
print(np.percentile(arr,75))
print(np.percentile(arr,100))
print(np.sum(arr))