x=10
y=20
print("Addition:",x+y)
print("Subtraction:",x-y)
print("Multiplication:",x*y)
print("Division:",x/y)
print("Floor Division:",x//y)
print("Modulus:",x%y)
print("Exponentiation:",x**y)
print("Comparison (x>y):",x>y)
print("Comparison (x<y):",x<y)
print("Comparison (x==y):",x==y)
print("Comparison (x!=y):",x!=y)
print("Logical AND:",(x>5) and (y<25))
print("Logical OR:",(x>15) or (y<25))
print("NOt operator:",not(x>5))
print("Bitwise AND:",x & y)
print("Bitwise OR:",x | y)
print("Bitwise XOR:",x ^ y)
print("Bitwise NOT:",~x)
print("Left Shift:",x << 2)
print("Right Shift:",x >> 2)